### ISSUE TITLE
Rora partial reads on non aligned offsets

### ISSUE THREAD

**Issue by domsj** [openvstorage/gobjfs#12]
We might issue reads that are not nicely (4kb) aligned, for lengths that are not a nice multiple of 4kb.
If this doesn't work the code does a fallback to the slow path (via proxy) which is undesirable.

**Comment by sanjosh** [comment]
The buffer which is passed to a file which has been opened in O_DIRECT mode has to be 512-byte aligned.   In case of reads coming in via gIOExecFile, the caller must ensure that this buffer is actually aligned in this fashion.  Previously, this was ensured by Alba ocaml caller.  Now the same must be done by the NetworkXioServer layer when it allocates a local buffer.   It should adjust the offset and size as appropriate.

Changes to be done
1) In NetworkXioIOHandler, align the offset and buffer to be 512-byte aligned before sending to gIOExecFile.  While returning response, copy only the appropriate region. 

2) In gIOExecFile, return error if caller has not passed an offset and buffer which is NOT 512-byte aligned.

Documentation
1) add description of expected argument values to javadoc in header file of gIOExecFile.

Write tests
1) client side : issue partial reads at non-512 byte offset and size and it should succeed
2) server side : issue partial reads using gIOExecFile api at non-512 byte offset and buffer address and it should fail because gIOExecFile expects all callers to send offset and buffer which are 512-byte aligned.

**Comment by domsj** [comment]
Some more clarification about why we want/need this:
In a perfectly configured alba (fragment size, policy) it should be possible for the reads to be nicely aligned.
I think the exact requirement is that fragment_size/k = multiple of 512.
As soon as this is not the case the majority of rora partial reads will fail and take the slow path.
(The majority = all except those of the first fragment of the first chunk)
